/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kami.view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import br.com.kami.dto.SalaoDTO;
import br.com.kami.ctr.SalaoCTR;
import br.com.kami.dto.CabeleireiroDTO;
import br.com.kami.ctr.CabeleireiroCTR;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Aluno
 */
public class SalaoVIEW extends javax.swing.JInternalFrame {

    SalaoCTR salaoCTR = new SalaoCTR(); //Cria um objeto locacaoCTR
    SalaoDTO salaoDTO = new SalaoDTO(); //Cria um objeto locacaoDTO
    CabeleireiroCTR cabeleireiroCTR = new CabeleireiroCTR(); //Cria um objeto carroCTR
    CabeleireiroDTO cabeleireiroDTO = new CabeleireiroDTO(); //Cria um objeto carroDTO

    ResultSet rs; //Variavel usada para preenchimeto da tabela e dos campos
    int gravar_alterar; //Variavel usada para saber se esta alterando o incluindo
    DefaultTableModel modelo_jtl_consultar_salao; //Variavel para guardar o modelo da tabela

    public SalaoVIEW(CabeleireiroDTO cabeleireiroDTO) {
        this.cabeleireiroDTO = cabeleireiroDTO;
        initComponents();
        liberaCampos(false);
        //Chama o método liberaBotoes
        liberaBotoes(true, false, false, false);
        //Atribui um modelo para manipular a tabela 
        modelo_jtl_consultar_salao = (DefaultTableModel) jtl_consultar_salao.getModel();

        System.out.println(this.cabeleireiroDTO.getId_cab());

        try {
            this.setSelected(true);
            this.setMaximizable(true);
            this.setMaximum(true);
        } catch (Exception e) {

        }
    }

    /**
     * Método para centralizar o internalFrame.
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }//Fecha método setPosicao()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeSalao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cidadeSalao = new javax.swing.JTextField();
        telefoneSalao = new javax.swing.JTextField();
        ruaSalao = new javax.swing.JTextField();
        bairroSalao = new javax.swing.JTextField();
        numSalao = new javax.swing.JTextField();
        urlfoto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_consultar_salao = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        pesquisa_salao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("DADOS");

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(67, 49, 40));

        jPanel6.setBackground(new java.awt.Color(146, 105, 82));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(355, 467));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));

        nomeSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nomeSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeSalaoActionPerformed(evt);
            }
        });
        nomeSalao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeSalaoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cidade:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rua:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Bairro:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("N°: ");

        cidadeSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cidadeSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cidadeSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeSalaoActionPerformed(evt);
            }
        });
        cidadeSalao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cidadeSalaoKeyPressed(evt);
            }
        });

        telefoneSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        telefoneSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneSalaoActionPerformed(evt);
            }
        });
        telefoneSalao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefoneSalaoKeyPressed(evt);
            }
        });

        ruaSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ruaSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ruaSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaSalaoActionPerformed(evt);
            }
        });
        ruaSalao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ruaSalaoKeyPressed(evt);
            }
        });

        bairroSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bairroSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bairroSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroSalaoActionPerformed(evt);
            }
        });
        bairroSalao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bairroSalaoKeyPressed(evt);
            }
        });

        numSalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numSalao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numSalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSalaoActionPerformed(evt);
            }
        });

        urlfoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urlfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        urlfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlfotoActionPerformed(evt);
            }
        });
        urlfoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                urlfotoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("URL foto:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ruaSalao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeSalao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefoneSalao)
                            .addComponent(nomeSalao)
                            .addComponent(bairroSalao, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(urlfoto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(numSalao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(nomeSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefoneSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urlfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cidadeSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ruaSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bairroSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numSalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        jPanel7.setBackground(new java.awt.Color(146, 105, 82));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jtl_consultar_salao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cabeleireiro", "Nome", "Telefone", "Cidade", "Rua", "Bairro", "N°", "URLfoto"
            }
        ));
        jtl_consultar_salao.getTableHeader().setReorderingAllowed(false);
        jtl_consultar_salao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_consultar_salaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtl_consultar_salao);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Salão:");

        pesquisa_salao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisa_salao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pesquisa_salao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_salaoActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/pesquisar.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisa_salao, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pesquisa_salao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPesquisar)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/sair.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kami/view/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalvar)
                        .addGap(198, 198, 198))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(28, 28, 28)
                        .addComponent(btnCancelar)
                        .addGap(73, 73, 73)
                        .addComponent(btnVoltar)))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(146, 105, 82));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(146, 105, 82));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setText("CADASTRO - SALÃO");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeSalaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (verificaPreenchimentoGeral()) {
            if (gravar_alterar == 1) {
                gravar();
                gravar_alterar = 0;
            } else {
                if (gravar_alterar == 2) {
                    alterar();
                    preencheTabela(pesquisa_salao.getText(), cabeleireiroDTO);
                    gravar_alterar = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Erro no sistema!!!");
                }
            }
            limpaCampos();
            liberaCampos(false);
            liberaBotoes(true, false, false, false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
        limpaCampos();
        liberaCampos(false);
        liberaBotoes(true, false, false, true);
        preencheTabela(pesquisa_salao.getText(), cabeleireiroDTO);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void pesquisa_salaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_salaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_salaoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        preencheTabela(pesquisa_salao.getText(), cabeleireiroDTO);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        // TODO add your handling code here:  
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cidadeSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeSalaoActionPerformed

    private void telefoneSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneSalaoActionPerformed

    private void ruaSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaSalaoActionPerformed

    private void bairroSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroSalaoActionPerformed

    private void numSalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSalaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSalaoActionPerformed

    private void urlfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlfotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlfotoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        liberaCampos(false);
        modelo_jtl_consultar_salao.setNumRows(0);
        liberaBotoes(true, false, false, true);
        gravar_alterar = 0;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        liberaCampos(true);
        liberaBotoes(false, true, false, true);
        gravar_alterar = 1;
        System.out.println(gravar_alterar);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jtl_consultar_salaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_consultar_salaoMouseClicked
        // TODO add your handling code here:
        preencheCampos(Integer.parseInt(String.valueOf(jtl_consultar_salao.getValueAt(jtl_consultar_salao.getSelectedRow(), 0))));
        liberaBotoes(false, true, true, true);
    }//GEN-LAST:event_jtl_consultar_salaoMouseClicked

    private void nomeSalaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeSalaoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(nomeSalao, 40);
    }//GEN-LAST:event_nomeSalaoKeyPressed

    private void telefoneSalaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneSalaoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(telefoneSalao, 40);
    }//GEN-LAST:event_telefoneSalaoKeyPressed

    private void urlfotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlfotoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(urlfoto, 1000);
    }//GEN-LAST:event_urlfotoKeyPressed

    private void cidadeSalaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidadeSalaoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(cidadeSalao, 40);
    }//GEN-LAST:event_cidadeSalaoKeyPressed

    private void ruaSalaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ruaSalaoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(ruaSalao, 40);
    }//GEN-LAST:event_ruaSalaoKeyPressed

    private void bairroSalaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bairroSalaoKeyPressed
        // TODO add your handling code here:
        verificaTamanho(bairroSalao, 40);
    }//GEN-LAST:event_bairroSalaoKeyPressed

    /**
     * Método utilizado para gravar os dados da locacao.
     */
    private void gravar() {
        try {
            cabeleireiroDTO.setId_cab(this.cabeleireiroDTO.getId_cab());
            salaoDTO.setNomeSalao(nomeSalao.getText());
            salaoDTO.setTelefoneSalao(telefoneSalao.getText());
            salaoDTO.setCidadeSalao(cidadeSalao.getText());
            salaoDTO.setUrlfoto(urlfoto.getText());
            salaoDTO.setRuaSalao(ruaSalao.getText());
            salaoDTO.setBairroSalao(bairroSalao.getText());
            salaoDTO.setNumSalao(Integer.parseInt(numSalao.getText()));

            JOptionPane.showMessageDialog(null, salaoCTR.inserirSalao(salaoDTO, cabeleireiroDTO));
        }//Fecha método gravar()
        catch (Exception e) {
            System.out.print("Erro ao gravar" + e.getMessage());
        }
    }

    private void alterar() {

        salaoDTO.setNomeSalao(nomeSalao.getText());
        salaoDTO.setTelefoneSalao(telefoneSalao.getText());
        salaoDTO.setCidadeSalao(cidadeSalao.getText());
        salaoDTO.setUrlfoto(urlfoto.getText());
        salaoDTO.setRuaSalao(ruaSalao.getText());
        salaoDTO.setBairroSalao(bairroSalao.getText());
        salaoDTO.setNumSalao(Integer.parseInt(numSalao.getText()));

        JOptionPane.showMessageDialog(null, salaoCTR.alterarSalao(salaoDTO));
    }

    private void excluir() {
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o Salão?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,
                    salaoCTR.excluirSalao(salaoDTO)
            );
        }
    }//Fecha método excluir()

    private void preencheTabela(String nomeSalao, CabeleireiroDTO cabeleireiroDTO) {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_salao.setNumRows(0);

            salaoDTO.setNomeSalao(nomeSalao);

            rs = salaoCTR.consultarSalao(salaoDTO, cabeleireiroDTO, 1);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_salao.addRow(new Object[]{
                    rs.getString("id_salao"),
                    rs.getString("nomeCab"),
                    rs.getString("nomeSalao"),
                    rs.getString("telefoneSalao"),
                    rs.getString("cidadeSalao"),
                    rs.getString("ruaSalao"),
                    rs.getString("bairroSalao"),
                    rs.getString("numSalao"),
                    rs.getString("urlfoto")
                });
            }
        } catch (Exception e) {
            System.out.println("Erro SQL: " + e.getMessage());
        }
    }//Fecha método preencheTabelaSalao()

    private void preencheCampos(int id_salao) {
        try {
            salaoDTO.setId_salao(id_salao);
            rs = salaoCTR.consultarSalao(salaoDTO, cabeleireiroDTO, 2); //2 = é a pesquisa no id na classe DAO
            if (rs.next()) {
                limpaCampos();

                nomeSalao.setText(rs.getString("nomeSalao"));
                telefoneSalao.setText(rs.getString("telefoneSalao"));
                urlfoto.setText(rs.getString("urlfoto"));
                cidadeSalao.setText(rs.getString("cidadeSalao"));
                ruaSalao.setText(rs.getString("ruaSalao"));
                bairroSalao.setText(rs.getString("bairroSalao"));
                numSalao.setText(rs.getString("numSalao"));

                gravar_alterar = 2;
                liberaCampos(true);
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheCampos(int id_salao)

    private void liberaCampos(boolean a) {
        nomeSalao.setEnabled(a);
        telefoneSalao.setEnabled(a);
        urlfoto.setEnabled(a);
        cidadeSalao.setEnabled(a);
        ruaSalao.setEnabled(a);
        bairroSalao.setEnabled(a);
        numSalao.setEnabled(a);
    }//Fecha método liberaCampos(boolean a)

    private void limpaCampos() {
        nomeSalao.setText("");
        telefoneSalao.setText("");
        urlfoto.setText("");
        cidadeSalao.setText("");
        ruaSalao.setText("");
        bairroSalao.setText("");
        numSalao.setText("");
    }//Fecha método liberaCampos(boolean a)

    private void liberaBotoes(boolean a, boolean b, boolean c, boolean d) {
        btnNovo.setEnabled(a);
        btnSalvar.setEnabled(b);
        btnExcluir.setEnabled(c);
        btnCancelar.setEnabled(d);
    }//Fecha método liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e)

    private boolean verificaPreenchimentoGeral() {
        if (nomeSalao.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "O campo Nome deve ser preenchido");
            nomeSalao.requestFocus();
            return false;
        } else {
            if (telefoneSalao.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "O campo Telefone deve ser preenchido");
                telefoneSalao.requestFocus();
                return false;
            } else {
                if (cidadeSalao.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(null, "O campo Cidade deve ser preenchido");
                    cidadeSalao.requestFocus();
                    return false;
                } else {
                    if (ruaSalao.getText().equalsIgnoreCase("")) {
                        JOptionPane.showMessageDialog(null, "O campo Rua deve ser preenchido");
                        ruaSalao.requestFocus();
                        return false;
                    } else {
                        if (bairroSalao.getText().equalsIgnoreCase("")) {
                            JOptionPane.showMessageDialog(null, "O campo Bairro deve ser preenchido");
                            bairroSalao.requestFocus();
                            return false;
                        } else {
                            if (numSalao.getText().equalsIgnoreCase("")) {
                                JOptionPane.showMessageDialog(null, "O campo Nº deve ser preenchido");
                                numSalao.requestFocus();
                                return false;
                            } else {
                                return true;
                            }//Fecha else nomeSalao
                        }//Fecha else telefoneSalao
                    }//Fecha else cidadeSalao
                }//Fecha else ruaSalao
            }//Fecha else bairroSalao
        }//Fecha else numSalao
    }//Fecha método verificaPreenchimentoGeral()

    /**
     * Método utilizado para limitar o maximo de caracteres nos campos.
     *
     * @param jtextfield, JTextField que recebe o campo.
     * @param maximo, int com o tamanho maximo do campo.
     */
    private void verificaTamanho(JTextField jtextfield, int maximo) {
        String tamanho = jtextfield.getText();
        if (tamanho.length() >= maximo) {
            jtextfield.setText(jtextfield.getText().substring(0, maximo - 1));
        }
    }//Fecha método verificaTamanho(JTextField jtextfield, int maximo)  

    /**
     * Método utilizado para limitar o maximo de caracteres nos campos.
     *
     * @param jtextfield, JTextField que recebe o campo.
     * @param maximo, int com o tamanho maximo do campo.
     */
    private void verificaTamanho(JTextArea jtextarea, int maximo) {
        String tamanho = jtextarea.getText();
        if (tamanho.length() >= maximo) {
            jtextarea.setText(jtextarea.getText().substring(0, maximo - 1));
        }
    }//Fecha método verificaTamanho(JTextArea jtextarea, int maximo

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroSalao;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField cidadeSalao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtl_consultar_salao;
    private javax.swing.JTextField nomeSalao;
    private javax.swing.JTextField numSalao;
    private javax.swing.JTextField pesquisa_salao;
    private javax.swing.JTextField ruaSalao;
    private javax.swing.JTextField telefoneSalao;
    private javax.swing.JTextField urlfoto;
    // End of variables declaration//GEN-END:variables
}
